# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetMatrixSizeFromUTSize <- function(ut_size) {
    .Call('MVNMixtureLRVB_GetMatrixSizeFromUTSize', PACKAGE = 'MVNMixtureLRVB', ut_size)
}

GetUpperTriangularIndex <- function(p1, p2) {
    .Call('MVNMixtureLRVB_GetUpperTriangularIndex', PACKAGE = 'MVNMixtureLRVB', p1, p2)
}

ConvertSymmetricMatrixToVector <- function(x) {
    .Call('MVNMixtureLRVB_ConvertSymmetricMatrixToVector', PACKAGE = 'MVNMixtureLRVB', x)
}

ConvertVectorToSymmetricMatrix <- function(x_vec) {
    .Call('MVNMixtureLRVB_ConvertVectorToSymmetricMatrix', PACKAGE = 'MVNMixtureLRVB', x_vec)
}

GetZCoordinate <- function(n, k, n_tot, k_tot) {
    .Call('MVNMixtureLRVB_GetZCoordinate', PACKAGE = 'MVNMixtureLRVB', n, k, n_tot, k_tot)
}

GetXCoordinate <- function(n, p, n_tot, p_tot) {
    .Call('MVNMixtureLRVB_GetXCoordinate', PACKAGE = 'MVNMixtureLRVB', n, p, n_tot, p_tot)
}

LinearlyPackParameters <- function(mu, lambda, pi) {
    .Call('MVNMixtureLRVB_LinearlyPackParameters', PACKAGE = 'MVNMixtureLRVB', mu, lambda, pi)
}

LinearlyUnpackParameters <- function(par, k_tot, p_tot) {
    .Call('MVNMixtureLRVB_LinearlyUnpackParameters', PACKAGE = 'MVNMixtureLRVB', par, k_tot, p_tot)
}

PackVBParameters <- function(e_z, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi) {
    .Call('MVNMixtureLRVB_PackVBParameters', PACKAGE = 'MVNMixtureLRVB', e_z, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi)
}

UnpackVBParameters <- function(par, n_tot, p_tot, k_tot) {
    .Call('MVNMixtureLRVB_UnpackVBParameters', PACKAGE = 'MVNMixtureLRVB', par, n_tot, p_tot, k_tot)
}

UnpackVBThetaParameters <- function(par, n_tot, p_tot, k_tot) {
    .Call('MVNMixtureLRVB_UnpackVBThetaParameters', PACKAGE = 'MVNMixtureLRVB', par, n_tot, p_tot, k_tot)
}

GetCoreVBThetaIndices <- function(n_tot, p_tot, k_tot) {
    .Call('MVNMixtureLRVB_GetCoreVBThetaIndices', PACKAGE = 'MVNMixtureLRVB', n_tot, p_tot, k_tot)
}

PackXParameters <- function(x) {
    .Call('MVNMixtureLRVB_PackXParameters', PACKAGE = 'MVNMixtureLRVB', x)
}

UnpackXParameters <- function(par, n_tot, p_tot) {
    .Call('MVNMixtureLRVB_UnpackXParameters', PACKAGE = 'MVNMixtureLRVB', par, n_tot, p_tot)
}

InvertLinearizedMatrices <- function(par_mat) {
    .Call('MVNMixtureLRVB_InvertLinearizedMatrices', PACKAGE = 'MVNMixtureLRVB', par_mat)
}

LogDeterminantOfLinearizedMatrices <- function(par_mat) {
    .Call('MVNMixtureLRVB_LogDeterminantOfLinearizedMatrices', PACKAGE = 'MVNMixtureLRVB', par_mat)
}

GetVectorizedOuterProductMatrix <- function(mat) {
    .Call('MVNMixtureLRVB_GetVectorizedOuterProductMatrix', PACKAGE = 'MVNMixtureLRVB', mat)
}

CppLgamma <- function(x) {
    .Call('MVNMixtureLRVB_CppLgamma', PACKAGE = 'MVNMixtureLRVB', x)
}

CppDigamma <- function(x) {
    .Call('MVNMixtureLRVB_CppDigamma', PACKAGE = 'MVNMixtureLRVB', x)
}

CppTrigamma <- function(x) {
    .Call('MVNMixtureLRVB_CppTrigamma', PACKAGE = 'MVNMixtureLRVB', x)
}

CppMultivariateLgamma <- function(x, p) {
    .Call('MVNMixtureLRVB_CppMultivariateLgamma', PACKAGE = 'MVNMixtureLRVB', x, p)
}

CppMultivariateDigamma <- function(x, p) {
    .Call('MVNMixtureLRVB_CppMultivariateDigamma', PACKAGE = 'MVNMixtureLRVB', x, p)
}

CppMultivariateTrigamma <- function(x, p) {
    .Call('MVNMixtureLRVB_CppMultivariateTrigamma', PACKAGE = 'MVNMixtureLRVB', x, p)
}

MVNLogLikelihoodPoint <- function(x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi) {
    .Call('MVNMixtureLRVB_MVNLogLikelihoodPoint', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi)
}

MVNLogLikelihoodPointWithX2 <- function(x, x2, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi) {
    .Call('MVNMixtureLRVB_MVNLogLikelihoodPointWithX2', PACKAGE = 'MVNMixtureLRVB', x, x2, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi)
}

LogPriorMu <- function(e_mu, e_mu2, mu_prior_mean, mu_prior_info) {
    .Call('MVNMixtureLRVB_LogPriorMu', PACKAGE = 'MVNMixtureLRVB', e_mu, e_mu2, mu_prior_mean, mu_prior_info)
}

LogPriorLambda <- function(e_lambda, e_log_det_lambda, lambda_prior_v_inv, lambda_prior_n) {
    .Call('MVNMixtureLRVB_LogPriorLambda', PACKAGE = 'MVNMixtureLRVB', e_lambda, e_log_det_lambda, lambda_prior_v_inv, lambda_prior_n)
}

LogPriorPi <- function(e_log_pi, pi_prior_alpha) {
    .Call('MVNMixtureLRVB_LogPriorPi', PACKAGE = 'MVNMixtureLRVB', e_log_pi, pi_prior_alpha)
}

MarginalLogLikelihoodWithPriors <- function(x, mu, lambda, pi, use_mu_prior, use_lambda_prior, use_pi_prior, mu_prior_mean, mu_prior_info, lambda_prior_v_inv, lambda_prior_n, pi_prior_alpha, debug = FALSE) {
    .Call('MVNMixtureLRVB_MarginalLogLikelihoodWithPriors', PACKAGE = 'MVNMixtureLRVB', x, mu, lambda, pi, use_mu_prior, use_lambda_prior, use_pi_prior, mu_prior_mean, mu_prior_info, lambda_prior_v_inv, lambda_prior_n, pi_prior_alpha, debug)
}

MarginalLogLikelihood <- function(x, mu, lambda, pi) {
    .Call('MVNMixtureLRVB_MarginalLogLikelihood', PACKAGE = 'MVNMixtureLRVB', x, mu, lambda, pi)
}

CompleteLogLikelihoodWithPriors <- function(x, z, mu, mu2, lambda, log_det_lambda, log_pi, use_mu_prior, use_lambda_prior, use_pi_prior, mu_prior_mean, mu_prior_info, lambda_prior_v_inv, lambda_prior_n, pi_prior_alpha, debug = FALSE) {
    .Call('MVNMixtureLRVB_CompleteLogLikelihoodWithPriors', PACKAGE = 'MVNMixtureLRVB', x, z, mu, mu2, lambda, log_det_lambda, log_pi, use_mu_prior, use_lambda_prior, use_pi_prior, mu_prior_mean, mu_prior_info, lambda_prior_v_inv, lambda_prior_n, pi_prior_alpha, debug)
}

CompleteLogLikelihoodWithX2 <- function(x, x2, z, mu, mu2, lambda, log_det_lambda, log_pi, debug = FALSE) {
    .Call('MVNMixtureLRVB_CompleteLogLikelihoodWithX2', PACKAGE = 'MVNMixtureLRVB', x, x2, z, mu, mu2, lambda, log_det_lambda, log_pi, debug)
}

WishartEntropy <- function(log_det_v, n_par, p_tot) {
    .Call('MVNMixtureLRVB_WishartEntropy', PACKAGE = 'MVNMixtureLRVB', log_det_v, n_par, p_tot)
}

DirichletEntropy <- function(alpha) {
    .Call('MVNMixtureLRVB_DirichletEntropy', PACKAGE = 'MVNMixtureLRVB', alpha)
}

MultinouliiEntropy <- function(p_mat) {
    .Call('MVNMixtureLRVB_MultinouliiEntropy', PACKAGE = 'MVNMixtureLRVB', p_mat)
}

GetVariationalEntropy <- function(z, mu, mu2, lambda_par, n_par, pi_par) {
    .Call('MVNMixtureLRVB_GetVariationalEntropy', PACKAGE = 'MVNMixtureLRVB', z, mu, mu2, lambda_par, n_par, pi_par)
}

UpdateMuPosterior <- function(x, e_lambda_inv_mat, e_z, use_prior, e_lambda_mat, mu_prior_mean, mu_prior_info) {
    .Call('MVNMixtureLRVB_UpdateMuPosterior', PACKAGE = 'MVNMixtureLRVB', x, e_lambda_inv_mat, e_z, use_prior, e_lambda_mat, mu_prior_mean, mu_prior_info)
}

UpdateLambdaPosterior <- function(x, e_mu, e_mu2, e_z, use_prior, lambda_prior_v_inv, lambda_prior_n) {
    .Call('MVNMixtureLRVB_UpdateLambdaPosterior', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_z, use_prior, lambda_prior_v_inv, lambda_prior_n)
}

WishartELogDet <- function(lambda_par, n_par) {
    .Call('MVNMixtureLRVB_WishartELogDet', PACKAGE = 'MVNMixtureLRVB', lambda_par, n_par)
}

GetELogDirichlet <- function(alpha) {
    .Call('MVNMixtureLRVB_GetELogDirichlet', PACKAGE = 'MVNMixtureLRVB', alpha)
}

GetLogDirichletCovariance <- function(alpha) {
    .Call('MVNMixtureLRVB_GetLogDirichletCovariance', PACKAGE = 'MVNMixtureLRVB', alpha)
}

GetLogPiVariance <- function(pi_par) {
    .Call('MVNMixtureLRVB_GetLogPiVariance', PACKAGE = 'MVNMixtureLRVB', pi_par)
}

GetMuVariance <- function(mu_par, mu2_par) {
    .Call('MVNMixtureLRVB_GetMuVariance', PACKAGE = 'MVNMixtureLRVB', mu_par, mu2_par)
}

GetWishartLinearCovariance <- function(w_par, n_par) {
    .Call('MVNMixtureLRVB_GetWishartLinearCovariance', PACKAGE = 'MVNMixtureLRVB', w_par, n_par)
}

GetWishartLinearLogDetCovariance <- function(w_par) {
    .Call('MVNMixtureLRVB_GetWishartLinearLogDetCovariance', PACKAGE = 'MVNMixtureLRVB', w_par)
}

GetWishartLogDetVariance <- function(n_par, p) {
    .Call('MVNMixtureLRVB_GetWishartLogDetVariance', PACKAGE = 'MVNMixtureLRVB', n_par, p)
}

GetLambdaVariance <- function(lambda_par, n_par) {
    .Call('MVNMixtureLRVB_GetLambdaVariance', PACKAGE = 'MVNMixtureLRVB', lambda_par, n_par)
}

GetXVariance <- function(x) {
    .Call('MVNMixtureLRVB_GetXVariance', PACKAGE = 'MVNMixtureLRVB', x)
}

GetXVarianceSubset <- function(x, x_indices) {
    .Call('MVNMixtureLRVB_GetXVarianceSubset', PACKAGE = 'MVNMixtureLRVB', x, x_indices)
}

GetZMatrixInPlace <- function(z, x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi) {
    .Call('MVNMixtureLRVB_GetZMatrixInPlace', PACKAGE = 'MVNMixtureLRVB', z, x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi)
}

GetZMatrix <- function(x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi) {
    .Call('MVNMixtureLRVB_GetZMatrix', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_lambda, e_log_det_lambda, e_log_pi)
}

GetSingleZCovariance <- function(z) {
    .Call('MVNMixtureLRVB_GetSingleZCovariance', PACKAGE = 'MVNMixtureLRVB', z)
}

GetZCovariance <- function(z_mat) {
    .Call('MVNMixtureLRVB_GetZCovariance', PACKAGE = 'MVNMixtureLRVB', z_mat)
}

GetHThetaZ <- function(x, e_mu, e_mu2, e_lambda) {
    .Call('MVNMixtureLRVB_GetHThetaZ', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_lambda)
}

GetHThetaTheta <- function(x, e_z) {
    .Call('MVNMixtureLRVB_GetHThetaTheta', PACKAGE = 'MVNMixtureLRVB', x, e_z)
}

GetHThetaX <- function(e_z, e_mu, e_lambda) {
    .Call('MVNMixtureLRVB_GetHThetaX', PACKAGE = 'MVNMixtureLRVB', e_z, e_mu, e_lambda)
}

GetHThetaXSubset <- function(e_z, e_mu, e_lambda, x_indices) {
    .Call('MVNMixtureLRVB_GetHThetaXSubset', PACKAGE = 'MVNMixtureLRVB', e_z, e_mu, e_lambda, x_indices)
}

GetHZX <- function(n_tot, e_mu, e_lambda) {
    .Call('MVNMixtureLRVB_GetHZX', PACKAGE = 'MVNMixtureLRVB', n_tot, e_mu, e_lambda)
}

GetHZXSubset <- function(n_tot, e_mu, e_lambda, x_indices) {
    .Call('MVNMixtureLRVB_GetHZXSubset', PACKAGE = 'MVNMixtureLRVB', n_tot, e_mu, e_lambda, x_indices)
}

GetHZDelta <- function(e_z) {
    .Call('MVNMixtureLRVB_GetHZDelta', PACKAGE = 'MVNMixtureLRVB', e_z)
}

PredictPerturbationEffect <- function(x, tx_cov, x_n, x_p, delta) {
    .Call('MVNMixtureLRVB_PredictPerturbationEffect', PACKAGE = 'MVNMixtureLRVB', x, tx_cov, x_n, x_p, delta)
}

GetLRVBCorrectionTerm <- function(x, e_mu, e_mu2, e_lambda, e_z, theta_cov, verbose = FALSE) {
    .Call('MVNMixtureLRVB_GetLRVBCorrectionTerm', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_lambda, e_z, theta_cov, verbose)
}

CPPGetLRVBCovariance <- function(x, e_mu, e_mu2, e_lambda, e_z, theta_cov, verbose = FALSE) {
    .Call('MVNMixtureLRVB_CPPGetLRVBCovariance', PACKAGE = 'MVNMixtureLRVB', x, e_mu, e_mu2, e_lambda, e_z, theta_cov, verbose)
}

CPPGetLRVBCovarianceFromCorrection <- function(lrvb_correction, theta_cov, verbose = FALSE) {
    .Call('MVNMixtureLRVB_CPPGetLRVBCovarianceFromCorrection', PACKAGE = 'MVNMixtureLRVB', lrvb_correction, theta_cov, verbose)
}

CPPGetLeverageScores <- function(z_cov, x_cov, htx, htz, hzx, lrvb_correction, theta_cov, verbose = FALSE) {
    .Call('MVNMixtureLRVB_CPPGetLeverageScores', PACKAGE = 'MVNMixtureLRVB', z_cov, x_cov, htx, htz, hzx, lrvb_correction, theta_cov, verbose)
}

